name 'aggressivex-mysql'
version '0.9.1'
source 'git://github.com/aggressivex/puppet-mysql.git'
author 'Luis M. Hdez - Aggressivex NetWorks'
license 'MIT'
summary 'Httpd module'
description 'Httpd module'
project_page 'http://github.com/aggressivex/puppet-mysql'