class conf {
  
  $setup = {
    'conf_path' => '/etc/httpd/conf.d/',
    'conf_template' => 'httpd/httpd.auto.erb',
    'conf_vhost_include_path' => '/etc/httpd/conf.d/vhost.conf',    
    'conf_vhost_include_pattern' => '#Include /var/www/project/host/conf/httpd/*',
    'conf_vhost_template' => 'vhost.default.erb'
  }

  $default = {
    'ServerTokens'         => 'SO',
    'PidFile'              => 'run/httpd.pid',
    'ServerRoot'           => '/etc/httpd',
    'Include'              => 'conf.d/*.conf',
    'ServerName'           => 'localhost.localdomain',
    'Listen'               => '192.168.33.10:80',
    'User'                 => 'apache',
    'Group'                => 'www-data',
    'Timeout'              => '120',
    'KeepAlive'            => 'Off',
    'MaxKeepAliveRequests' => '100',
    'KeepAliveTimeout'     => '15',
    'ifModule prefork.c' => {
      'StartServers'        => '8',
      'MinSpareServers'     => '5',
      'MaxSpareServers'     => '20',
      'ServerLimit'         => '256',
      'MaxClients'          => '256',
      'MaxRequestsPerChild' => '4000'
    },
    'ifModule worker.c' => {
      'StartServers'        => '2',
      'MaxClients'          => '150',
      'MinSpareThreads'     => '25',
      'MaxSpareThreads'     => '75',
      'ThreadsPerChild'     => '25',
      'MaxRequestsPerChild' => '0'
    },
    'DirectoryIndex' => 'DirectoryIndex index.html index.html.var',
    'AccessFileName' => '.htaccess',
    'TypesConfig'    => '/etc/mime.types',
    'DefaultType'    => 'text/plain',    
    'Directory /' => {
      'Options'       => 'FollowSymLinks',
      'AllowOverride' => 'None',
    },
    'Directory "/var/www/html"' => {
      'Options'       => 'FollowSymLinks',
      'AllowOverride' => 'None',
      'Order'         => 'allow,deny',
      'Allow'         => 'from all',
    },
    'IfModule mod_userdir.c' => {
      'UserDir'       => 'disable',
      'AllowOverride' => 'None',
      'Order'         => 'allow,deny',
      'Allow'         => 'from all',
    },
    'Files ~ "^\.ht"' => {
      'Order' => 'allow,deny',
      'Deny'  => 'from all',
    },
    'IfModule mod_mime_magic.c' => {
      'MIMEMagicFile' => 'conf/magic',
    },
    'ErrorLog'        => 'logs/error_log',
    'LogLevel'        => 'warn',
    'HostnameLookups' => 'Off',
    'CustomLog'       => 'logs/access_log combined',
    'ServerSignature' => 'On',
    'Alias'           => '/icons/ "/var/www/icons/"',
    'ScriptAlias'     => '/cgi-bin/ "/var/www/cgi-bin/"',
    'Alias /error/'   => '"/var/www/error/"',
    'IndexOptions'    => 'FancyIndexing VersionSort NameWidth=* HTMLTable',
    'IndexIgnore'     => '.??* *~ *# HEADER* README* RCS CVS *,v *,t',
    'Directory "/var/www/icons"' => {
      'Options' => 'Indexes MultiViews',
      'Order'  => 'allow,deny',
      'Allow'  => 'from all',
    },
    'Directory "/var/www/cgi-bin"' => {
      'AllowOverride' => 'None',
      'Options'  => 'None',
      'Order'  => 'allow,deny',
      'Allow'  => 'from all',
    },
    'IfModule mod_dav_fs.c' => {
      'DAVLockDB' => '/var/lib/dav/lockdb',
    },
    'LogFormat' => [
      '"%h %l %u %t \"%r\"\'] %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined',
      '"%h %l %u %t \"%r\"\'] %>s %b" common',
      '"%{Referer}i -> %U" referer',
      '"%{User-agent}i" agent',
    ],
    'AddIconByEncoding' => '(CMP,/icons/compressed.gif) x-compress x-gzip',
    'AddIconByType' => [
      '(TXT,/icons/text.gif) text/*',
      '(IMG,/icons/image2.gif) image/*',
      '(SND,/icons/sound2.gif) audio/*',
      '(VID,/icons/movie.gif) video/*',
    ],
    'AddIcon' => [
      '/icons/binary.gif .bin .exe',
      '/icons/binhex.gif .hqx',
      '/icons/tar.gif .tar',
      '/icons/world2.gif .wrl .wrl.gz .vrml .vrm .iv',
      '/icons/compressed.gif .Z .z .tgz .gz .zip',
      '/icons/a.gif .ps .ai .eps',
      '/icons/layout.gif .html .shtml .htm .pdf',
      '/icons/text.gif .txt',
      '/icons/c.gif .c',
      '/icons/p.gif .pl .py',
      '/icons/f.gif .for',
      '/icons/dvi.gif .dvi',
      '/icons/uuencoded.gif .uu',
      '/icons/script.gif .conf .sh .shar .csh .ksh .tcl',
      '/icons/tex.gif .tex',
      '/icons/bomb.gif core',
      '/icons/back.gif ..',
      '/icons/hand.right.gif README',
      '/icons/folder.gif ^^DIRECTORY^^',
      '/icons/blank.gif ^^BLANKICON^^',
    ],
    'DefaultIcon' => '/icons/unknown.gif',
    'ReadmeName'  => 'README.html',
    'HeaderName'  => 'HEADER.html',
    'AddLanguage' => [
      'ca .ca',
      'cs .cz .cs',
      'da .dk',
      'de .de',
      'el .el',
      'en .en',
      'eo .eo',
      'es .es',
      'et .et',
      'fr .fr',
      'he .he',
      'hr .hr',
      'it .it',
      'ja .ja',
      'ko .ko',
      'ltz .ltz',
      'nl .nl',
      'nn .nn',
      'no .no',
      'pl .po',
      'pt .pt',
      'pt-BR .pt-br',
      'ru .ru',
      'sv .sv',
      'zh-CN .zh-cn',
      'zh-TW .zh-tw',    
    ],
    'LanguagePriority' => 'en ca cs da de el eo es et fr he hr it ja ko ltz nl nn no pl pt pt-BR ru sv zh-CN zh-TW',
    'BrowserMatch' => [
      '"Mozilla/2" nokeepalive',
      '"MSIE 4\.0b2;" nokeepalive downgrade-1.0 force-response-1.0',
      '"RealPlayer 4\.0" force-response-1.0',
      '"Java/1\.0" force-response-1.0',
      '"JDK/1\.0" force-response-1.0',
      '"Microsoft Data Access Internet Publishing Provider" redirect-carefully',
      '"MS FrontPage" redirect-carefully',
      '"^WebDrive" redirect-carefully',
      '"^WebDAVFS/1.[0123]" redirect-carefully',
      '"^gnome-vfs/1.0" redirect-carefully',
      '"^XML Spy" redirect-carefully',
      '"^Dreamweaver-WebDAV-SCM1" redirect-carefully'
    ],
    'LoadModule' => [
      'auth_basic_module modules/mod_auth_basic.so',
      'auth_digest_module modules/mod_auth_digest.so',
      'authn_file_module modules/mod_authn_file.so',
      'authn_alias_module modules/mod_authn_alias.so',
      'authn_anon_module modules/mod_authn_anon.so',
      'authn_dbm_module modules/mod_authn_dbm.so',
      'authn_default_module modules/mod_authn_default.so',
      'authz_host_module modules/mod_authz_host.so',
      'authz_user_module modules/mod_authz_user.so',
      'authz_owner_module modules/mod_authz_owner.so',
      'authz_groupfile_module modules/mod_authz_groupfile.so',
      'authz_dbm_module modules/mod_authz_dbm.so',
      'authz_default_module modules/mod_authz_default.so',
      'ldap_module modules/mod_ldap.so',
      'authnz_ldap_module modules/mod_authnz_ldap.so',
      'include_module modules/mod_include.so',
      'log_config_module modules/mod_log_config.so',
      'logio_module modules/mod_logio.so',
      'env_module modules/mod_env.so',
      'ext_filter_module modules/mod_ext_filter.so',
      'mime_magic_module modules/mod_mime_magic.so',
      'expires_module modules/mod_expires.so',
      'deflate_module modules/mod_deflate.so',
      'headers_module modules/mod_headers.so',
      'usertrack_module modules/mod_usertrack.so',
      'setenvif_module modules/mod_setenvif.so',
      'mime_module modules/mod_mime.so',
      'dav_module modules/mod_dav.so',
      'status_module modules/mod_status.so',
      'autoindex_module modules/mod_autoindex.so',
      'info_module modules/mod_info.so',
      'dav_fs_module modules/mod_dav_fs.so',
      'vhost_alias_module modules/mod_vhost_alias.so',
      'negotiation_module modules/mod_negotiation.so',
      'dir_module modules/mod_dir.so',
      'actions_module modules/mod_actions.so',
      'speling_module modules/mod_speling.so',
      'userdir_module modules/mod_userdir.so',
      'alias_module modules/mod_alias.so',
      'rewrite_module modules/mod_rewrite.so',
      'proxy_module modules/mod_proxy.so',
      'proxy_balancer_module modules/mod_proxy_balancer.so',
      'proxy_ftp_module modules/mod_proxy_ftp.so',
      'proxy_http_module modules/mod_proxy_http.so',
      'proxy_connect_module modules/mod_proxy_connect.so',
      'cache_module modules/mod_cache.so',
      'suexec_module modules/mod_suexec.so',
      'disk_cache_module modules/mod_disk_cache.so',
      'cgi_module modules/mod_cgi.so',
      'version_module modules/mod_version.so',    
    ],
  }

}